version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: property_api_user
      POSTGRES_PASSWORD: KAhQcgVkQbXa6BZOue70WHLp6W676gxy
      POSTGRES_DB: property_api

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://property_api_user:KAhQcgVkQbXa6BZOue70WHLp6W676gxy@dpg-cicm612ip7vnjjkrb9qg-a.oregon-postgres.render.com/property_api

volumes:
  pgdata:
