version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: property_api_user
      POSTGRES_PASSWORD: KAhQcgVkQbXa6BZOue70WHLp6W676gxy
      POSTGRES_DB: property_api
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://property_api_user:KAhQcgVkQbXa6BZOue70WHLp6W676gxy@db/property_api

volumes:
  pgdata:
