databases:
    -name: postgres
    ipAllowList: []

services:
    -typpe: Web
    name: property-api
    env: ruby
    build command: "./bin/render.sh"
    start command: bundle exec rails s
      envVars:
        - key: RAILS_MASTER_KEY
          sync: false
        - key: DATABASE_URL
          fromDatabase:
            name: postgres
            property: connectionString
    - type: redis
      name: redis
      ipAllowList: []
      plan: free
      maxMemoryPolicy: noeviction